version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_banco_central
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco_central_fabio
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
